// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXORzAXdtpxL-vjZ7JoZKinBwnhVVGMEo',
    appId: '1:623161404842:web:84efe11769e48484c0cfd3',
    messagingSenderId: '623161404842',
    projectId: 'music-production-a0368',
    authDomain: 'music-production-a0368.firebaseapp.com',
    storageBucket: 'music-production-a0368.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvNrPfwqo6o4buSFEWOmhaxg46wiec_SU',
    appId: '1:623161404842:android:0e80f4c4153c2b05c0cfd3',
    messagingSenderId: '623161404842',
    projectId: 'music-production-a0368',
    storageBucket: 'music-production-a0368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN3z9z7KlauGnYTRXDWVxyVqeouP6YI0g',
    appId: '1:623161404842:ios:048911703daace63c0cfd3',
    messagingSenderId: '623161404842',
    projectId: 'music-production-a0368',
    storageBucket: 'music-production-a0368.firebasestorage.app',
    iosBundleId: 'com.example.musicProduction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN3z9z7KlauGnYTRXDWVxyVqeouP6YI0g',
    appId: '1:623161404842:ios:048911703daace63c0cfd3',
    messagingSenderId: '623161404842',
    projectId: 'music-production-a0368',
    storageBucket: 'music-production-a0368.firebasestorage.app',
    iosBundleId: 'com.example.musicProduction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXORzAXdtpxL-vjZ7JoZKinBwnhVVGMEo',
    appId: '1:623161404842:web:a0994660f4bed56ac0cfd3',
    messagingSenderId: '623161404842',
    projectId: 'music-production-a0368',
    authDomain: 'music-production-a0368.firebaseapp.com',
    storageBucket: 'music-production-a0368.firebasestorage.app',
  );
}
